/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gssteam2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Yashwee
 */
public class foodInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form foodInfoFrame
     */
    public foodInfoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        foodname = new javax.swing.JTextField();
        foodfat = new javax.swing.JTextField();
        foodcarb = new javax.swing.JTextField();
        foodcal = new javax.swing.JTextField();
        foodfiber = new javax.swing.JTextField();
        btnretrieve = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Food Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Fats");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Carbs");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setText("Fiber");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel5.setText("Calories");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        foodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodnameActionPerformed(evt);
            }
        });
        getContentPane().add(foodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 130, -1));

        foodfat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodfatActionPerformed(evt);
            }
        });
        getContentPane().add(foodfat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 130, -1));
        getContentPane().add(foodcarb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, -1));
        getContentPane().add(foodcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, -1));
        getContentPane().add(foodfiber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, -1));

        btnretrieve.setText("Retrieve");
        btnretrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretrieveActionPerformed(evt);
            }
        });
        getContentPane().add(btnretrieve, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 170, 30));

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnretrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretrieveActionPerformed
         String un=foodname.getText();
          Connection conn = null;
         PreparedStatement pstmt=null;
         ResultSet rs= null;
          try{
             Class.forName("com.mysql.jdbc.Driver");
              conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/foodDatabase?useSSL=false", "root", "gssteam2" );
              pstmt = conn.prepareStatement("select * from foodTable WHERE FoodTableName=?");
              pstmt.setString(1,un);
              rs = pstmt.executeQuery();
              while(rs.next()){
           
                  foodname.setText(rs.getString("FoodTableName"));
                 foodfat.setText(rs.getString("FoodTableFat"));
                 foodcarb.setText(rs.getString("FoodTableCarb"));
                 foodcal.setText(rs.getString("FoodTableCal"));
                 foodfiber.setText(rs.getString("FoodTableFiber"));
              
              }
          }  catch(Exception e){
           
              JOptionPane.showMessageDialog(null, e);
                
          }
            finally{
              try{
                  conn.close();
                  pstmt.close();
                  rs.close();
                  
              }  catch (Exception e) {
                  
              }
          }
    }//GEN-LAST:event_btnretrieveActionPerformed

    private void foodnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodnameActionPerformed

    private void foodfatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodfatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodfatActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
                 foodname.setText(null);
                 foodfat.setText(null);
                 foodcarb.setText(null);
                 foodcal.setText(null);
                 foodfiber.setText(null);
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodInfoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnretrieve;
    private javax.swing.JTextField foodcal;
    private javax.swing.JTextField foodcarb;
    private javax.swing.JTextField foodfat;
    private javax.swing.JTextField foodfiber;
    private javax.swing.JTextField foodname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
