/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gssteam2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Yashwee
 */
public class userJFrame extends javax.swing.JFrame {

    /**
     * Creates new form userJFrame
     */
    public userJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_bgr = new javax.swing.JTextField();
        txt_food = new javax.swing.JTextField();
        txt_mealCategory = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_time = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 33, -1, -1));

        jLabel2.setText("Meal Category");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 77, -1, -1));

        jLabel3.setText("Blood Glucose Reading");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 129, -1, -1));

        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 135, -1));
        getContentPane().add(txt_bgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 135, -1));

        txt_food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_foodActionPerformed(evt);
            }
        });
        getContentPane().add(txt_food, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 135, -1));

        txt_mealCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mealCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(txt_mealCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 30));

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 150, 30));

        jLabel5.setText("Food");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 185, -1, -1));
        getContentPane().add(txt_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 140, 20));

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 30));

        btn_next.setText("Nutrition Counter");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        getContentPane().add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_foodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_foodActionPerformed

    private void txt_mealCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mealCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mealCategoryActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
       String name = txt_name.getText();
       String mealCategory = txt_mealCategory.getText();
       String bgr = txt_bgr.getText();
       String food = txt_food.getText();
        String time = txt_time.getText();
       Connection conn = null;
       PreparedStatement pstmt = null;
       try{
              //Class.forName("com.mysql.jdbc.Driver");
              conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/foodDatabase?useSSL=false", "root", "gssteam2" );
              pstmt = conn.prepareStatement("insert into userData(name, meal_category, bgr, food, time) values(?, ?, ?, ?, ?)"); 
              pstmt.setString(1, name);
              pstmt.setString(2, mealCategory);
              pstmt.setString(3, bgr);
              pstmt.setString(4, food);
              pstmt.setString(5, time);
              
              int i = pstmt.executeUpdate();
              
              if(i>1){
                 JOptionPane.showMessageDialog(null, "Data is saved"); 
              }
              else{
                   JOptionPane.showMessageDialog(null, "Data is saved");
              }
       
       } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
                txt_name.setText(null);
                txt_mealCategory.setText(null);
                 txt_bgr.setText(null);
                txt_food.setText(null);
                 txt_time.setText(null);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
      new foodInfoFrame().setVisible(true);
      //this.setVisible(false);
    }//GEN-LAST:event_btn_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_bgr;
    private javax.swing.JTextField txt_food;
    private javax.swing.JTextField txt_mealCategory;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_time;
    // End of variables declaration//GEN-END:variables
}
